language: c

sudo: false

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - gcc-multilib
    - valgrind
    - cmake
    - git
    - libev-dev
    - doxygen

script:
    - mkdir build && cd build && cmake .. && make && make doc
