language: c

sudo: false

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - gcc-multilib
    - valgrind
    - cmake
    - git
    - libev-dev
    - doxygen
    - redis-server
    - redis-tools

script:
  - mkdir build && cd build && cmake .. && make && make doc && make CTEST_OUTPUT_ON_FAILURE=1 test
